# Generated by Django 3.2.6 on 2021-09-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100)),
                ('subaccount', models.CharField(max_length=100)),
            ],
        ),
    ]
